// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Attachment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Attachment ) UnmarshalJSON([]byte) error { return nil }
func ( Attachment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Attachment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Attachment *Attachment

func ( AttachmentData ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AttachmentData ) UnmarshalJSON([]byte) error { return nil }
func ( AttachmentData ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AttachmentData ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AttachmentData *AttachmentData
