package models

import "errors"

var (
	WrongPassword                       = errors.New("WrongPassword")
	NotFound                            = errors.New("NotFound")
	InternalError                       = errors.New("InternalError")
	ExpiredToken                        = errors.New("ExpiredToken")
	NoToken                             = errors.New("NoToken")
	NoAuthData                          = errors.New("NoAuthData")
	InvalidToken                        = errors.New("InvalidToken")
	WrongData                           = errors.New("WrongData")
	Unauthorized                        = errors.New("Unauthorized")
	Forbbiden                           = errors.New("Forbidden")
	WrongLoginLength                    = errors.New("wrong login length")
	WrongLoginSymbols                   = errors.New("wrong login contains black symbols")
	WrongNameLength                     = errors.New("wrong username length")
	WrongNameSymbols                    = errors.New("wrong username contains black symbols")
	WrongNameHasNoLetter                = errors.New("wrong username has no letter")
	WrongCreatorNameHasNoLetter         = errors.New("wrong creator name has no letter")
	WrongCreatorNameLength              = errors.New("wrong creator name length")
	WrongCreatorDescriptionLength       = errors.New("wrong creator description length")
	WrongCreatorNameSymbols             = errors.New("wrong creator name contains black symbols")
	WrongPasswordLength                 = errors.New("wrong password length")
	WrongPasswordSymbols                = errors.New("wrong password contains black symbols")
	PasswordHasNoNumber                 = errors.New("wrong password has no number")
	WrongAimDescriptionLength           = errors.New("wrong aim description length")
	WrongAimDescriptionSymbols          = errors.New("wrong aim description contains black symbols")
	WrongPostTitleLength                = errors.New("wrong post title length")
	WrongPostTextLength                 = errors.New("wrong post text length")
	WrongPostTitleSymbols               = errors.New("wrong post title contains black symbols")
	WrongPostTextSymbols                = errors.New("wrong post text contains black symbols")
	WrongSubscriptionTitleLength        = errors.New("wrong subscription title length")
	WrongSubscriptionDescriptionLength  = errors.New("wrong subscription description length")
	WrongSubscriptionDescriptionSymbols = errors.New("wrong subscription description contains black symbols")
	WrongSubscriptionTitleSymbols       = errors.New("wrong subscription title contains black symbols")
)
