// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_1_4from5/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAttachmentUsecase is a mock of AttachmentUsecase interface.
type MockAttachmentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentUsecaseMockRecorder
}

// MockAttachmentUsecaseMockRecorder is the mock recorder for MockAttachmentUsecase.
type MockAttachmentUsecaseMockRecorder struct {
	mock *MockAttachmentUsecase
}

// NewMockAttachmentUsecase creates a new mock instance.
func NewMockAttachmentUsecase(ctrl *gomock.Controller) *MockAttachmentUsecase {
	mock := &MockAttachmentUsecase{ctrl: ctrl}
	mock.recorder = &MockAttachmentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentUsecase) EXPECT() *MockAttachmentUsecaseMockRecorder {
	return m.recorder
}

// CreateAttachs mocks base method.
func (m *MockAttachmentUsecase) CreateAttachs(postID uuid.UUID, attachments ...models.AttachmentData) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{postID}
	for _, a := range attachments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAttachs", varargs...)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachs indicates an expected call of CreateAttachs.
func (mr *MockAttachmentUsecaseMockRecorder) CreateAttachs(postID interface{}, attachments ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{postID}, attachments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachs", reflect.TypeOf((*MockAttachmentUsecase)(nil).CreateAttachs), varargs...)
}

// DeleteAttachsByID mocks base method.
func (m *MockAttachmentUsecase) DeleteAttachsByID(attachmentIDs ...uuid.UUID) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range attachmentIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAttachsByID", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachsByID indicates an expected call of DeleteAttachsByID.
func (mr *MockAttachmentUsecaseMockRecorder) DeleteAttachsByID(attachmentIDs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachsByID", reflect.TypeOf((*MockAttachmentUsecase)(nil).DeleteAttachsByID), attachmentIDs...)
}

// DeleteAttachsByPostID mocks base method.
func (m *MockAttachmentUsecase) DeleteAttachsByPostID(postID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachsByPostID", postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachsByPostID indicates an expected call of DeleteAttachsByPostID.
func (mr *MockAttachmentUsecaseMockRecorder) DeleteAttachsByPostID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachsByPostID", reflect.TypeOf((*MockAttachmentUsecase)(nil).DeleteAttachsByPostID), postID)
}

// MockAttachmentRepo is a mock of AttachmentRepo interface.
type MockAttachmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentRepoMockRecorder
}

// MockAttachmentRepoMockRecorder is the mock recorder for MockAttachmentRepo.
type MockAttachmentRepoMockRecorder struct {
	mock *MockAttachmentRepo
}

// NewMockAttachmentRepo creates a new mock instance.
func NewMockAttachmentRepo(ctrl *gomock.Controller) *MockAttachmentRepo {
	mock := &MockAttachmentRepo{ctrl: ctrl}
	mock.recorder = &MockAttachmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentRepo) EXPECT() *MockAttachmentRepoMockRecorder {
	return m.recorder
}

// CreateAttach mocks base method.
func (m *MockAttachmentRepo) CreateAttach(postID, attachID uuid.UUID, attachmentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttach", postID, attachID, attachmentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttach indicates an expected call of CreateAttach.
func (mr *MockAttachmentRepoMockRecorder) CreateAttach(postID, attachID, attachmentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttach", reflect.TypeOf((*MockAttachmentRepo)(nil).CreateAttach), postID, attachID, attachmentType)
}

// DeleteAttachByID mocks base method.
func (m *MockAttachmentRepo) DeleteAttachByID(attachID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachByID", attachID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachByID indicates an expected call of DeleteAttachByID.
func (mr *MockAttachmentRepoMockRecorder) DeleteAttachByID(attachID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachByID", reflect.TypeOf((*MockAttachmentRepo)(nil).DeleteAttachByID), attachID)
}

// DeleteAttachByPostID mocks base method.
func (m *MockAttachmentRepo) DeleteAttachByPostID(postID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachByPostID", postID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAttachByPostID indicates an expected call of DeleteAttachByPostID.
func (mr *MockAttachmentRepoMockRecorder) DeleteAttachByPostID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachByPostID", reflect.TypeOf((*MockAttachmentRepo)(nil).DeleteAttachByPostID), postID)
}
