// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_1_4from5/internal/models"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAttachmentUsecase is a mock of AttachmentUsecase interface.
type MockAttachmentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentUsecaseMockRecorder
}

// MockAttachmentUsecaseMockRecorder is the mock recorder for MockAttachmentUsecase.
type MockAttachmentUsecaseMockRecorder struct {
	mock *MockAttachmentUsecase
}

// NewMockAttachmentUsecase creates a new mock instance.
func NewMockAttachmentUsecase(ctrl *gomock.Controller) *MockAttachmentUsecase {
	mock := &MockAttachmentUsecase{ctrl: ctrl}
	mock.recorder = &MockAttachmentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentUsecase) EXPECT() *MockAttachmentUsecaseMockRecorder {
	return m.recorder
}

// CreateAttaches mocks base method.
func (m *MockAttachmentUsecase) CreateAttaches(ctx context.Context, attachments ...models.AttachmentData) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range attachments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAttaches", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttaches indicates an expected call of CreateAttaches.
func (mr *MockAttachmentUsecaseMockRecorder) CreateAttaches(ctx interface{}, attachments ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, attachments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttaches", reflect.TypeOf((*MockAttachmentUsecase)(nil).CreateAttaches), varargs...)
}

// DeleteAttaches mocks base method.
func (m *MockAttachmentUsecase) DeleteAttaches(ctx context.Context, attachments ...models.AttachmentData) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range attachments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAttaches", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttaches indicates an expected call of DeleteAttaches.
func (mr *MockAttachmentUsecaseMockRecorder) DeleteAttaches(ctx interface{}, attachments ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, attachments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttaches", reflect.TypeOf((*MockAttachmentUsecase)(nil).DeleteAttaches), varargs...)
}

// DeleteAttachesByPostID mocks base method.
func (m *MockAttachmentUsecase) DeleteAttachesByPostID(ctx context.Context, postID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachesByPostID", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttachesByPostID indicates an expected call of DeleteAttachesByPostID.
func (mr *MockAttachmentUsecaseMockRecorder) DeleteAttachesByPostID(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachesByPostID", reflect.TypeOf((*MockAttachmentUsecase)(nil).DeleteAttachesByPostID), ctx, postID)
}

// MockAttachmentRepo is a mock of AttachmentRepo interface.
type MockAttachmentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentRepoMockRecorder
}

// MockAttachmentRepoMockRecorder is the mock recorder for MockAttachmentRepo.
type MockAttachmentRepoMockRecorder struct {
	mock *MockAttachmentRepo
}

// NewMockAttachmentRepo creates a new mock instance.
func NewMockAttachmentRepo(ctrl *gomock.Controller) *MockAttachmentRepo {
	mock := &MockAttachmentRepo{ctrl: ctrl}
	mock.recorder = &MockAttachmentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentRepo) EXPECT() *MockAttachmentRepoMockRecorder {
	return m.recorder
}

// CreateAttach mocks base method.
func (m *MockAttachmentRepo) CreateAttach(ctx context.Context, postID, attachID uuid.UUID, attachmentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttach", ctx, postID, attachID, attachmentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttach indicates an expected call of CreateAttach.
func (mr *MockAttachmentRepoMockRecorder) CreateAttach(ctx, postID, attachID, attachmentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttach", reflect.TypeOf((*MockAttachmentRepo)(nil).CreateAttach), ctx, postID, attachID, attachmentType)
}

// DeleteAttachesByPostID mocks base method.
func (m *MockAttachmentRepo) DeleteAttachesByPostID(ctx context.Context, postID uuid.UUID) ([]models.AttachmentData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttachesByPostID", ctx, postID)
	ret0, _ := ret[0].([]models.AttachmentData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAttachesByPostID indicates an expected call of DeleteAttachesByPostID.
func (mr *MockAttachmentRepoMockRecorder) DeleteAttachesByPostID(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttachesByPostID", reflect.TypeOf((*MockAttachmentRepo)(nil).DeleteAttachesByPostID), ctx, postID)
}
