name: SubMe build

on:
  push:
    branches:
      - rk2
      - main
jobs:
  linters-act:
    name: linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  tests-act:
    name: tests
    needs: linters-act
    if: ${{ job.status == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: go test ./...

  deploy:
    name: Deploy SubMe
    needs: tests-act
    if: ${{ job.status == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/2023_1_4from5 && git pull
      - name: Build containers
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/2023_1_4from5 && sudo docker-compose build
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/2023_1_4from5 && sudo docker-compose down && sudo docker-compose up -d